name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Kurtosis Developers name - for commit message'
        required: true
        type: string
      email:
        description: 'Kurtosis Developers email - for commit message'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Install Kudet
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kudet
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git Config
      run: |
        git config --global user.email "${{ inputs.username }}"
        git config --global user.name "${{ inputs.email }}"
      # Install the SSH key so that release command uses the ssh key to authenticate
    - name: Install the SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: unnecessary
    - name: Execute the release
      run:
        ssh-add ~/.ssh
        kudet release