name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Kurtosis Developers name - for commit message'
        required: true
        type: string
      email:
        description: 'Kurtosis Developers email - for commit message'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Install Kudet
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kudet
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git Config
      run: |
        git config --global user.email "Kurtosis Bot"
        git config --global user.name "hello@kurtosistech.com"
    - name: Execute the release
      # should we pass in kurtosis bots token or should we make it an env variable?
      run:
        kudet release