name: Release Workflow

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Install Kudet
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kudet
    - name: Setup Git User
      uses: fregante/setup-git-user@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Execute the release
      env: # Set the secret as an input
        ssh-key: ${{ secrets.SSH_KEY }}
      run:
        kudet release 
    
